# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mynetwork', '0003_auto_20170730_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mynetwork.UserProfile')),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='like_count',
        ),
        migrations.AddField(
            model_name='likes',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mynetwork.Post'),
        ),
    ]
