# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 01:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynetwork', '0004_auto_20170801_0246'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
    ]
